local lib = _G.LibTaxiData_Internal
if not lib then return end

local translations = {
    enUS = {
        COMMAND_HELP_NAME = "/ltd name <nodeID> - localized node name",
        COMMAND_HELP_NODE = "/ltd node <nodeID> [uiMapID] - localized name and full node details",
        COMMAND_HELP_NEAREST_PLAYER = "/ltd nearest - nearest taxi to the player and set a waypoint",
        COMMAND_HELP_NEAREST_MAP = "/ltd nearest <uiMapID> <x> <y> - nearest taxi from local map coordinates",
        COMMAND_HELP_NEAREST_WORLD = "/ltd nearest world <instanceID> <x> <y> - nearest taxi from world coordinates",
        COMMAND_HELP_WAYPOINT = "/ltd waypoint <nodeID> [uiMapID] - set a waypoint on a taxi node",
        STATE_UNKNOWN = "unknown",
        STATE_YES = "yes",
        STATE_NO = "no",
        UNKNOWN_NAME = "Unknown",
        UNKNOWN_NODE_ID = "Unknown node ID: %s",
        NODE_HEADER = "%s (node %d)",
        NODE_WORLD_POSITION = "world: instance=%d x=%.3f y=%.3f z=%.3f; APR: x=%.3f y=%.3f",
        NODE_MAP_POSITION = "map: uiMapID=%d x=%.4f y=%.4f (%.2f, %.2f)",
        NODE_CONDITIONS = "available=%s visible=%s conditions: node=%d visibility=%d specialIcon=%d flags=0x%X",
        NODE_MOUNTS = "mounts: Horde=%d Alliance=%d current=%s; characterBit=%d",
        NODE_OFFSETS = "offsets: map=(%.5f, %.5f) flight=(%.5f, %.5f); textureKit=%d minimapAtlas=%d facing=%.3f",
        NONE = "none",
        CANNOT_SET_WAYPOINT = "Cannot set waypoint: %s",
        WAYPOINT_SET = "Waypoint set: %s (node %d) on map %d at %.2f, %.2f",
        NO_MATCHING_TAXI = "No matching taxi node was found; check the coordinate format and node conditions.",
        NEAREST_TAXI = "Nearest: %s (node %d), %.1f yards",
        ERROR_UNKNOWN_NODE = "unknown node",
        ERROR_NO_COMPATIBLE_UI_MAP = "no compatible UI map",
        ERROR_WAYPOINT_API_UNAVAILABLE = "the waypoint API is unavailable",
        ERROR_WAYPOINT_REJECTED = "the waypoint was rejected",
        ERROR_INVALID_COORDINATES = "invalid coordinates",
        ERROR_MAP_API_UNAVAILABLE = "the map API is unavailable",
        ERROR_VECTOR_API_UNAVAILABLE = "the vector API is unavailable",
        ERROR_MAP_NOT_CONVERTIBLE = "the map cannot be converted",
        ERROR_OUTSIDE_MAP = "the coordinates are outside the map",
        ERROR_UNIT_POSITION_UNAVAILABLE = "the unit position is unavailable",
        ERROR_PLAYER_POSITION_UNAVAILABLE = "the player position is unavailable",
        ERROR_UNKNOWN = "unknown error (%s)",
    },
    frFR = {
        COMMAND_HELP_NAME = "/ltd name <nodeID> - nom localisé du nœud",
        COMMAND_HELP_NODE = "/ltd node <nodeID> [uiMapID] - nom localisé et détails complets du nœud",
        COMMAND_HELP_NEAREST_PLAYER = "/ltd nearest - taxi le plus proche du joueur et création d’un point de passage",
        COMMAND_HELP_NEAREST_MAP = "/ltd nearest <uiMapID> <x> <y> - taxi le plus proche depuis des coordonnées locales",
        COMMAND_HELP_NEAREST_WORLD = "/ltd nearest world <instanceID> <x> <y> - taxi le plus proche depuis des coordonnées mondiales",
        COMMAND_HELP_WAYPOINT = "/ltd waypoint <nodeID> [uiMapID] - créer un point de passage sur un nœud de taxi",
        STATE_UNKNOWN = "inconnu",
        STATE_YES = "oui",
        STATE_NO = "non",
        UNKNOWN_NAME = "Inconnu",
        UNKNOWN_NODE_ID = "ID de nœud inconnu : %s",
        NODE_HEADER = "%s (nœud %d)",
        NODE_WORLD_POSITION = "monde : instance=%d x=%.3f y=%.3f z=%.3f ; APR : x=%.3f y=%.3f",
        NODE_MAP_POSITION = "carte : uiMapID=%d x=%.4f y=%.4f (%.2f, %.2f)",
        NODE_CONDITIONS = "disponible=%s visible=%s conditions : nœud=%d visibilité=%d icôneSpéciale=%d flags=0x%X",
        NODE_MOUNTS = "montures : Horde=%d Alliance=%d actuelle=%s ; bitPersonnage=%d",
        NODE_OFFSETS = "décalages : carte=(%.5f, %.5f) vol=(%.5f, %.5f) ; textureKit=%d atlasMinicarte=%d orientation=%.3f",
        NONE = "aucune",
        CANNOT_SET_WAYPOINT = "Impossible de créer le point de passage : %s",
        WAYPOINT_SET = "Point de passage créé : %s (nœud %d), carte %d à %.2f, %.2f",
        NO_MATCHING_TAXI = "Aucun nœud de taxi correspondant n’a été trouvé ; vérifiez le format des coordonnées et les conditions du nœud.",
        NEAREST_TAXI = "Plus proche : %s (nœud %d), %.1f mètres",
        ERROR_UNKNOWN_NODE = "nœud inconnu",
        ERROR_NO_COMPATIBLE_UI_MAP = "aucune carte d’interface compatible",
        ERROR_WAYPOINT_API_UNAVAILABLE = "l’API de point de passage est indisponible",
        ERROR_WAYPOINT_REJECTED = "le point de passage a été refusé",
        ERROR_INVALID_COORDINATES = "coordonnées invalides",
        ERROR_MAP_API_UNAVAILABLE = "l’API de carte est indisponible",
        ERROR_VECTOR_API_UNAVAILABLE = "l’API vectorielle est indisponible",
        ERROR_MAP_NOT_CONVERTIBLE = "la carte ne peut pas être convertie",
        ERROR_OUTSIDE_MAP = "les coordonnées sont hors de la carte",
        ERROR_UNIT_POSITION_UNAVAILABLE = "la position de l’unité est indisponible",
        ERROR_PLAYER_POSITION_UNAVAILABLE = "la position du joueur est indisponible",
        ERROR_UNKNOWN = "erreur inconnue (%s)",
    },
}

local locale = GetLocale and GetLocale() or "enUS"
local selected = translations[locale] or {}
setmetatable(selected, { __index = translations.enUS })

lib.Localization = selected
